// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znngymbrvutdrhxvjrfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpubmd5bWJydnV0ZHJoeHZqcmZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4NjEyNDMsImV4cCI6MjA4OTQzNzI0M30.WqQbiQDBp0cIdABrpwCOqYMUYWA4Wlt_Y83fOUPOoWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});